//! `SeaORM` Entity, @generated by sea-orm-codegen for Telegraph notifications

use sea_orm::entity::prelude::*;
use chrono::Utc;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "notifications")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub title: String,
    pub content: Vec<u8>,
    pub content_type: String,
    pub is_read: bool,
    pub priority: i16,
    pub expires_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub read_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::notification_deliveries::Entity")]
    NotificationDeliveries,
}

impl Related<super::notification_deliveries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationDeliveries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    /// Get the content as a JSON string if content_type is application/json
    pub fn content_as_json(&self) -> Result<Option<String>, serde_json::Error> {
        if self.content_type == "application/json" {
            let json_str = String::from_utf8_lossy(&self.content);
            serde_json::from_str::<serde_json::Value>(&json_str)?;
            Ok(Some(json_str.to_string()))
        } else {
            Ok(None)
        }
    }

    /// Get the content as bytes
    pub fn content_as_bytes(&self) -> &[u8] {
        &self.content
    }

    /// Check if the notification is expired
    pub fn is_expired(&self) -> bool {
        if let Some(expires_at) = self.expires_at {
            Utc::now().naive_utc() > expires_at
        } else {
            false
        }
    }

    /// Mark as read
    pub fn mark_as_read(&mut self) {
        self.is_read = true;
        self.read_at = Some(Utc::now().naive_utc());
        self.updated_at = Utc::now().naive_utc();
    }
} 