sonar.projectKey=Djoe-Denne_IAMRusty
sonar.organization=djoe-denne06

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=AIForAll
sonar.projectVersion=1.0

# Rust workspace analysis.
sonar.sources=.
sonar.inclusions=**/*.rs
sonar.exclusions=target/**,**/target/**,**/.git/**,lcov.info
sonar.coverage.exclusions=**/tests/**,**/fixtures/**,**/migration/src/**,**/infra/src/repository/entity/**,rustycog/rustycog-testing/**,**/src/main.rs,**/setup/src/**,**/configuration/src/**,monolith/src/**,iam-events/src/**,hive-events/src/**,manifesto-events/src/**,apparatus-events/src/**
sonar.rust.lcov.reportPaths=lcov.info

sonar.rust.clippy.enabled=false
sonar.rust.clippyReport.reportPaths=target/sonar/clippy.json