//! `SeaORM` Entity, @generated by sea-orm-codegen for Telegraph notification deliveries

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "notification_deliveries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub notification_id: Uuid,
    pub delivery_method: String,
    pub status: String,
    pub attempt_count: i16,
    pub last_attempt_at: Option<DateTime<Utc>>,
    pub delivered_at: Option<DateTime<Utc>>,
    pub error_message: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::notifications::Entity",
        from = "Column::NotificationId",
        to = "super::notifications::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Notifications,
}

impl Related<super::notifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notifications.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DeliveryMethod {
    Email,
    Sms,
    Push,
    InApp,
}

impl From<DeliveryMethod> for String {
    fn from(method: DeliveryMethod) -> Self {
        match method {
            DeliveryMethod::Email => "email".to_string(),
            DeliveryMethod::Sms => "sms".to_string(),
            DeliveryMethod::Push => "push".to_string(),
            DeliveryMethod::InApp => "in_app".to_string(),
        }
    }
}

impl TryFrom<String> for DeliveryMethod {
    type Error = String;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        match value.as_str() {
            "email" => Ok(Self::Email),
            "sms" => Ok(Self::Sms),
            "push" => Ok(Self::Push),
            "in_app" => Ok(Self::InApp),
            _ => Err(format!("Invalid delivery method: {value}")),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DeliveryStatus {
    Pending,
    Sent,
    Delivered,
    Failed,
    Bounced,
}

impl From<DeliveryStatus> for String {
    fn from(status: DeliveryStatus) -> Self {
        match status {
            DeliveryStatus::Pending => "pending".to_string(),
            DeliveryStatus::Sent => "sent".to_string(),
            DeliveryStatus::Delivered => "delivered".to_string(),
            DeliveryStatus::Failed => "failed".to_string(),
            DeliveryStatus::Bounced => "bounced".to_string(),
        }
    }
}

impl TryFrom<String> for DeliveryStatus {
    type Error = String;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        match value.as_str() {
            "pending" => Ok(Self::Pending),
            "sent" => Ok(Self::Sent),
            "delivered" => Ok(Self::Delivered),
            "failed" => Ok(Self::Failed),
            "bounced" => Ok(Self::Bounced),
            _ => Err(format!("Invalid delivery status: {value}")),
        }
    }
}

impl Model {
    /// Check if delivery can be retried
    #[must_use]
    pub fn can_retry(&self) -> bool {
        matches!(self.status.as_str(), "pending" | "failed") && self.attempt_count < 3
    }

    /// Check if delivery is successful
    #[must_use]
    pub fn is_successful(&self) -> bool {
        matches!(self.status.as_str(), "sent" | "delivered")
    }

    /// Increment attempt count
    pub fn increment_attempt(&mut self) {
        self.attempt_count += 1;
        self.last_attempt_at = Some(Utc::now());
        self.updated_at = Utc::now();
    }

    /// Mark as delivered
    pub fn mark_delivered(&mut self) {
        self.status = DeliveryStatus::Delivered.into();
        self.delivered_at = Some(Utc::now());
        self.updated_at = Utc::now();
    }

    /// Mark as failed with error message
    pub fn mark_failed(&mut self, error: String) {
        self.status = DeliveryStatus::Failed.into();
        self.error_message = Some(error);
        self.updated_at = Utc::now();
    }
}
