use async_trait::async_trait;
use sea_orm::{ActiveModelTrait, ActiveValue, ColumnTrait, DatabaseConnection, EntityTrait, QueryFilter, QueryOrder};
use uuid::Uuid;

use {{SERVICE_NAME}}_domain::{
    DomainError, ExampleEntity, ExampleEntityRepository, EntityStatus,
};

use super::error_conversion::db_error_to_domain_error;

/// PostgreSQL implementation of ExampleEntityRepository
pub struct PostgresExampleEntityRepository {
    db: DatabaseConnection,
}

impl PostgresExampleEntityRepository {
    /// Create a new repository instance
    pub fn new(db: DatabaseConnection) -> Self {
        Self { db }
    }
}

#[async_trait]
impl ExampleEntityRepository for PostgresExampleEntityRepository {
    async fn find_by_id(&self, id: &Uuid) -> Result<Option<ExampleEntity>, DomainError> {
        let entity_model = entities::example_entity::Entity::find_by_id(*id)
            .one(&self.db)
            .await
            .map_err(db_error_to_domain_error)?;

        match entity_model {
            Some(model) => Ok(Some(model.try_into()?)),
            None => Ok(None),
        }
    }

    async fn find_by_name(&self, name: &str) -> Result<Vec<ExampleEntity>, DomainError> {
        let entity_models = entities::example_entity::Entity::find()
            .filter(entities::example_entity::Column::Name.contains(name))
            .order_by_asc(entities::example_entity::Column::Name)
            .all(&self.db)
            .await
            .map_err(db_error_to_domain_error)?;

        entity_models
            .into_iter()
            .map(|model| model.try_into())
            .collect()
    }

    async fn find_all(&self) -> Result<Vec<ExampleEntity>, DomainError> {
        let entity_models = entities::example_entity::Entity::find()
            .order_by_asc(entities::example_entity::Column::CreatedAt)
            .all(&self.db)
            .await
            .map_err(db_error_to_domain_error)?;

        entity_models
            .into_iter()
            .map(|model| model.try_into())
            .collect()
    }

    async fn find_all_active(&self) -> Result<Vec<ExampleEntity>, DomainError> {
        let entity_models = entities::example_entity::Entity::find()
            .filter(entities::example_entity::Column::Status.eq("active"))
            .order_by_asc(entities::example_entity::Column::CreatedAt)
            .all(&self.db)
            .await
            .map_err(db_error_to_domain_error)?;

        entity_models
            .into_iter()
            .map(|model| model.try_into())
            .collect()
    }

    async fn save(&self, entity: &ExampleEntity) -> Result<ExampleEntity, DomainError> {
        // Check if entity exists
        let existing = entities::example_entity::Entity::find_by_id(entity.id)
            .one(&self.db)
            .await
            .map_err(db_error_to_domain_error)?;

        let active_model = entities::example_entity::ActiveModel {
            id: ActiveValue::Set(entity.id),
            name: ActiveValue::Set(entity.name.clone()),
            description: ActiveValue::Set(entity.description.clone()),
            status: ActiveValue::Set(entity_status_to_string(&entity.status)),
            created_at: ActiveValue::Set(entity.created_at.naive_utc()),
            updated_at: ActiveValue::Set(entity.updated_at.naive_utc()),
        };

        let saved_model = if existing.is_some() {
            // Update existing entity
            active_model.update(&self.db).await
        } else {
            // Insert new entity
            active_model.insert(&self.db).await
        }
        .map_err(db_error_to_domain_error)?;

        saved_model.try_into()
    }

    async fn delete_by_id(&self, id: &Uuid) -> Result<(), DomainError> {
        entities::example_entity::Entity::delete_by_id(*id)
            .exec(&self.db)
            .await
            .map_err(db_error_to_domain_error)?;

        Ok(())
    }

    async fn exists_by_name(&self, name: &str) -> Result<bool, DomainError> {
        let count = entities::example_entity::Entity::find()
            .filter(entities::example_entity::Column::Name.eq(name))
            .count(&self.db)
            .await
            .map_err(db_error_to_domain_error)?;

        Ok(count > 0)
    }

    async fn count(&self) -> Result<i64, DomainError> {
        let count = entities::example_entity::Entity::find()
            .count(&self.db)
            .await
            .map_err(db_error_to_domain_error)?;

        Ok(count as i64)
    }
}

/// Database entities module (would be generated by sea-orm-cli)
mod entities {
    pub mod example_entity {
        use chrono::NaiveDateTime;
        use sea_orm::{entity::prelude::*, DeriveEntityModel};
        use uuid::Uuid;

        #[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
        #[sea_orm(table_name = "example_entities")]
        pub struct Model {
            #[sea_orm(primary_key, auto_increment = false)]
            pub id: Uuid,
            pub name: String,
            pub description: Option<String>,
            pub status: String,
            pub created_at: NaiveDateTime,
            pub updated_at: NaiveDateTime,
        }

        #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
        pub enum Relation {}

        impl ActiveModelBehavior for ActiveModel {}
    }
}

/// Convert domain entity status to database string
fn entity_status_to_string(status: &EntityStatus) -> String {
    match status {
        EntityStatus::Active => "active".to_string(),
        EntityStatus::Inactive => "inactive".to_string(),
        EntityStatus::Pending => "pending".to_string(),
        EntityStatus::Archived => "archived".to_string(),
    }
}

/// Convert database string to domain entity status
fn string_to_entity_status(status: &str) -> Result<EntityStatus, DomainError> {
    match status {
        "active" => Ok(EntityStatus::Active),
        "inactive" => Ok(EntityStatus::Inactive),
        "pending" => Ok(EntityStatus::Pending),
        "archived" => Ok(EntityStatus::Archived),
        _ => Err(DomainError::invalid_input(&format!(
            "Invalid entity status: {}",
            status
        ))),
    }
}

/// Convert database model to domain entity
impl TryFrom<entities::example_entity::Model> for ExampleEntity {
    type Error = DomainError;

    fn try_from(model: entities::example_entity::Model) -> Result<Self, Self::Error> {
        Ok(ExampleEntity {
            id: model.id,
            name: model.name,
            description: model.description,
            status: string_to_entity_status(&model.status)?,
            created_at: chrono::DateTime::from_naive_utc_and_offset(
                model.created_at,
                chrono::Utc,
            ),
            updated_at: chrono::DateTime::from_naive_utc_and_offset(
                model.updated_at,
                chrono::Utc,
            ),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use {{SERVICE_NAME}}_domain::ExampleEntity;

    #[test]
    fn test_entity_status_conversion() {
        let status = EntityStatus::Active;
        let status_string = entity_status_to_string(&status);
        assert_eq!(status_string, "active");

        let converted_back = string_to_entity_status(&status_string).unwrap();
        assert!(matches!(converted_back, EntityStatus::Active));
    }

    #[test]
    fn test_invalid_status_conversion() {
        let result = string_to_entity_status("invalid_status");
        assert!(result.is_err());
    }

    #[test]
    fn test_model_to_entity_conversion() {
        let model = entities::example_entity::Model {
            id: Uuid::new_v4(),
            name: "Test Entity".to_string(),
            description: Some("Test Description".to_string()),
            status: "active".to_string(),
            created_at: chrono::Utc::now().naive_utc(),
            updated_at: chrono::Utc::now().naive_utc(),
        };

        let entity: Result<ExampleEntity, DomainError> = model.try_into();
        assert!(entity.is_ok());

        let entity = entity.unwrap();
        assert_eq!(entity.name, "Test Entity");
        assert!(matches!(entity.status, EntityStatus::Active));
    }
} 