[request_definition]
r = sub, org, act
r2 = sub, org, member, act

[policy_definition]
p = sub, org, act
p2 = sub, org, member, act

[policy_effect]
e = some(where (p.eft == allow))
e2 = some(where (p.eft == allow))

[matchers]
m = (r.sub == p.sub && r.org == p.org && r.act == p.act)
m2 = (r2.sub == p2.sub && r2.org == p2.org && r2.member == p2.member && r2.act == p2.act)
