apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aiforall-local-apparatus
labels:
  - pairs: {aiforall.dev/profile: local-full}
    includeSelectors: false
    includeTemplates: true
resources:
  - ../../../../p4/operator.yaml
  - ../../../../p4/serviceaccounts.yaml
  - ../../../../p4/crd-admissionrecord.yaml
  - ../../../../p4/rbac-watch.yaml
  - ../../../../p4/rbac-admit-sign.yaml
  - resources.yaml
patches:
  - path: patches.yaml
