//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "project_member_role_permissions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: Uuid,
    pub member_id: Uuid,
    pub role_permission_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::project_members::Entity",
        from = "Column::MemberId",
        to = "super::project_members::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ProjectMembers,
    #[sea_orm(
        belongs_to = "super::role_permissions::Entity",
        from = "Column::RolePermissionId",
        to = "super::role_permissions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    RolePermissions,
}

impl Related<super::project_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectMembers.def()
    }
}

impl Related<super::role_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RolePermissions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
